version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stroke-predictor-frontend
    platform: linux/arm64/v8  # Specific for M1 Mac
    ports:
      - "8082:8082"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=8082
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8082"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped